name: Test Build
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies (GNU+Linux)
      if: runner.os == 'Linux' # how misleading
      run: sudo apt update && sudo apt install -y libncurses5-dev libncursesw5-dev build-essential cmake

    - name: Install Dependencies (MacOS)
      if: runner.os == 'MacOS'
      run: brew install ncurses cmake

    - name: Install Dependencies (Windows)
      if: runner.os == 'Windows'
      run: vcpkg install pdcurses:x64-windows getopt-win32:x64-windows

    - name: Configure CMake (Unix)
      if: runner.os != 'Windows'
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        cmake -B build -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cmake --build build --config Release
